name: Build, Scan, and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Get Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          load: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-tutorial:adam-${{ env.SHORT_SHA }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-tutorial:adam-${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-tutorial:adam-${{ env.SHORT_SHA }}